### ISSUE TITLE
No Arrows Random + Scores

### ISSUE THREAD

**Issue by aawalton** [Kylon99/NoArrowsRandom#2]
Love the mod, I pretty much rage quit Beat Saber when they disabled the beta and it was impossible to do no arrows random for a while.

As I was testing today, I noticed that turning on the No Arrows Random modifier appears to completely disable score submission. I get that for public leaderboards (ideally No Arrows Random would have it's own leaderboard, but it makes sense not to compare it with standard modes for now), but it also seemed to disable score submission locally, which means I can't tell if I did better this time than last time. Any chance we could at least get scores to save locally?

**Comment by Kylon99** [comment]
Unfortunately BS_Utils doesn't allow me to choose what kind of score submission to disable or not.  It's something I'd have to research with Kyle and Umbranox.  However, I'm considering opening a new scoreboard for NoArrowsRandom specifically.  Which also means more discussion.  It may come to nothing.  8)  We will see...
